#
# Makefile for 
#

SHELL = /bin/sh
SUBDIRS = avbi bioskbd et6k_nova etvtim ikbdmouse nova gfx_tt generic

srcdir = .
top_srcdir = ../
subdir = drivers

default: all

include $(top_srcdir)/CONFIGVARS
include $(top_srcdir)/RULES
include $(top_srcdir)/PHONY

all-here: 

# default overwrites

# default definitions
